version: '3.9'

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGODB_USER=mongo
      - MONGODB_PASS=secret
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    networks:
      - web-net
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8001:1234
    environment:
      - HOST=0.0.0.0
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - web-net
  backend:
    container_name: backend
    build: ./back
    ports:
      - 3333:3333
    platform: linux/x86_64
    working_dir: /back
    depends_on:
      - mongo
    restart: always
    networks:
      - web-net
  frontend:
    container_name: frontend
    build: ./front
    ports:
      - 3131:3131
    platform: linux/x86_64
    working_dir: /front
    depends_on:
      - backend
    restart: always
    networks:
      - web-net
volumes:
  data: {}
networks:
  web-net:
    name: web-net